######################## default configuration ####################
baseURL = "https://alexis-ribat.github.io/mon-portfolio-bi/" # VOTRE lien GitHub Pages
languageCode = "en-us"
title = "Ribat | BI"
theme = "port-hugo"
publishDir = "docs"      # INDISPENSABLE pour GitHub Pages
canonifyURLs = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"
[[params.plugins.css]]
link = "css/custom.css"
[[params.plugins.css]]
link = "https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/.min.js"
[[params.plugins.js]]
link = "https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js"
[[params.plugins.js]]
link = "plugins/lightbox/lightbox.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "#home" # Pointe vers le haut de page
weight = 1

[[menu.main]]
name = "About me"
URL = "#about"
weight = 2

[[menu.main]]
name = "Experience" # Ajout de l'expérience
URL = "#experience"
weight = 3

[[menu.main]]
name = "Skills" # Ajout des compétences
URL = "#skill"
weight = 4

[[menu.main]]
name = "Portfolio"
URL = "#portfolio"
weight = 5

[[menu.main]]
name = "Contact" # Ajout du contact
URL = "#contact"
weight = 6


#################### default parameters ################################
[params]
copyright = "Copyright Alexis Ribat &copy;"
# Meta data
description = "BI Engineer Portfolio"
author = "Alexis Ribat"
favicon = "images/favicon.png"
google_analytics = "" # Laissez vide pour l'instant

# IMPORTANT : J'ai mis des # devant les logos pour les désactiver.
# Comme ça, le site affichera juste votre titre "Ribat | BI" proprement.
# logo_light = "images/logo.svg"
# logo_dark = "images/logo-dark.svg"

# Preloader (L'animation de chargement)
[params.preloader]
enable = true
preloader = "images/preloader.gif"

############################# social site ########################

[[params.social]]
icon = "fab fa-linkedin"
link = "https://www.linkedin.com/in/votre-profil" # Mettez votre vrai lien !

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:votre-email@gmail.com" # Mettez votre email

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/Alexis-Ribat" # Votre GitHub

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true